
jobs:

  # Neko

  - job: BuildLinux
    pool:
      vmImage: 'ubuntu-16.04'
    container: haxe:4.1.2
    steps:
      - script: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib install hscript
          haxelib install flixel-ui
          haxelib install newgrounds
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib run lime build linux
        displayName: 'Compile'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'linuxOutput'
          targetPath: bin/Funkin.exe
  - job: BuildMac
    pool:
      vmImage: 'macOS-10.14'
    container: haxe:4.1.2
    steps:
      - script: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib install hscript
          haxelib install flixel-ui
          haxelib install newgrounds
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib run lime build mac
        displayName: 'Compile'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'macOutput'
          targetPath: bin/Funkin.exe
  - job: TestNekoLinux
    dependsOn: BuildLinux
    pool:
      vmImage: 'ubuntu-16.04'
    container: haxe:4.1.2
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: 'linuxOutput'
          targetPath: bin
      - script: bin/Funkin
        displayName: 'Test'

  - job: TestNekoMac
    dependsOn: BuildMac
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - checkout: none
      - script: brew install neko
        displayName: 'Install Neko'
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: 'macOutput'
          targetPath: bin
      - script: bin/Funkin.app
        displayName: 'Test'





  - job: BuildCppWindows
    pool:
      vmImage: 'windows-2019'
    steps:
      - powershell: |
          choco install --no-progress haxe -y
          $nekoPath = (Get-ChildItem C:/ProgramData/chocolatey/lib/neko/*/neko.dll -Recurse).Directory
          echo "##vso[task.setvariable variable=NEKOPATH]$nekoPath"

        displayName: 'Install Haxe'
      - script: |
          md "C:/artifacts"
          haxelib setup C:/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib install hscript
          haxelib install flixel-ui
          haxelib install newgrounds
          haxelib git polymod https://github.com/larsiusprime/polymod.git

        displayName: 'Install haxelibs'
      - script: haxelib run lime build windows
        displayName: 'Compile'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'cppWindowsOutput'
          targetPath: C:/artifacts


  - job: TestCppWindows
    dependsOn: BuildCppWindows
    pool:
      vmImage: 'windows-2019'
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: 'cppWindowsOutput'
          targetPath: bin
      - script: bin\Funkin.exe
        displayName: 'Test'
