  
jobs:

  # Neko

  - job: BuildNeko
    pool:
      vmImage: 'ubuntu-16.04'
    container: haxe:4.1.2
    steps:
      - script: |
          haxelib setup
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib install hscript
          haxelib install flixel-ui
          haxelib install newgrounds
          lime build neko
        displayName: 'Compile'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'nekoOutput'
          targetPath: bin/Funkin.exe

  - job: TestNekoLinux
    dependsOn: BuildNeko
    pool:
      vmImage: 'ubuntu-16.04'
    container: haxe:4.1.2
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: 'nekoOutput'
          targetPath: bin
      - script: neko bin/Funkin.exe
        displayName: 'Test'

  - job: TestNekoMac
    dependsOn: BuildNeko
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - checkout: none
      - script: brew install neko
        displayName: 'Install Neko'
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: 'nekoOutput'
          targetPath: bin
      - script: neko bin/Funkin.exe
        displayName: 'Test'



  

  - job: BuildCppWindows
    pool:
      vmImage: 'windows-2019'
    steps:
      - powershell: |
          choco install --no-progress haxe -y
          $nekoPath = (Get-ChildItem C:/ProgramData/chocolatey/lib/neko/*/neko.dll -Recurse).Directory
          echo "##vso[task.setvariable variable=NEKOPATH]$nekoPath"
        displayName: 'Install Haxe'
      - script: |
          haxelib setup C:/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib install hscript
          haxelib install flixel-ui
          haxelib install newgrounds
          

        displayName: 'Install haxelibs'
      - script: lime build windows
        displayName: 'Compile'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'cppWindowsOutput'
          targetPath: bin


  - job: TestCppWindows
    dependsOn: BuildCppWindows
    pool:
      vmImage: 'windows-2019'
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: 'cppWindowsOutput'
          targetPath: bin
      - script: bin\Funkin.exe
        displayName: 'Test'

 
