blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/thepercentageguy/Unnamed-FNF-Engine/discussions/categories/q-a
    about: Please ask and answer questions here.
