name: Crash Report
description: Report Crashes here
title: "[CRASH]: "
labels: ["ufnf crash"]
assignees:
  - thepercentageguy
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please put the steps to reprodruce the crash here!
  - type: textarea
    id: logs
    attributes:
      label: Error
      description: Please either; A: attach the crash log. B: Upload a screenshot of the error box OR C: paste the contents of the crash log here.
    validations:
      required: true
