name: Build Game for HTML5
on: workflow_dispatch
jobs:
  HTML5:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true
          persist-credentials: false
      - name: Configure git
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
      - name: Compile
        run: haxelib run lime build html5 -minify
      - name: Upload To Website
        run: |
          cd ..
          git clone https://github.com/FunkinWeb/FunkinWeb.github.io
          cd FunkinWeb.github.io
          mv index.html ..
          rm -rf *
          mv ${{ github.workspace }}/export/release/html5/bin/index.html ${{ github.workspace }}/export/release/html5/bin/game.html
          mv ${{ github.workspace }}/export/release/html5/bin/* .
          mv ../index.html .
          git config --global user.name "mcagabe19"
          git config --global user.email "egzozu.be.bas@gmail.com"
          git add .
          git commit -m "Uploaded via actions."
          git push -u origin main
