name: Superlinter
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      - run: |
          haxelib install haxelint
          haxelint -s source
