name: Superformatter
on: push
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      - run: haxelib install formatter &&  haxelib run formatter -s source Preloader.hx
      - uses: zwaldowski/git-commit-action@v1
